### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [tinysec/js-capstone#1]
is this a Javascript binding for Capstone? will you provide a README?

keep it up, cheers.

**Comment by tinysec** [comment]
yes , is a node js binding for the Capstone 3.0.5-rc2.
because the current node js  bindings is very old  , so i make a new one.
but only x86/x64 bindings is current provide.

**Comment by aquynh** [comment]
nice to see the JS bindings for Keystone & Unicorn as well! let me know if you need any helps from the cores, cheers.
